# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


# from PyQt5 import QtCore, QtGui, QtWidgets

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 545)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(24,24,36);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu_container = QFrame(self.centralwidget)
        self.side_menu_container.setMinimumSize(QSize(0, 0))
        self.side_menu_container.setMaximumSize(QSize(0, 16777215))
        self.side_menu_container.setStyleSheet("background-color: rgb(9,5,13);")
        self.side_menu_container.setFrameShape(QFrame.StyledPanel)
        self.side_menu_container.setFrameShadow(QFrame.Raised)
        self.side_menu_container.setObjectName("side_menu_container")
        self.verticalLayout_2 = QVBoxLayout(self.side_menu_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.slide_menu = QFrame(self.side_menu_container)
        self.slide_menu.setMinimumSize(QSize(198, 0))
        self.slide_menu.setFrameShape(QFrame.StyledPanel)
        self.slide_menu.setFrameShadow(QFrame.Raised)
        self.slide_menu.setObjectName("slide_menu")
        self.verticalLayout_5 = QVBoxLayout(self.slide_menu)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_7 = QFrame(self.slide_menu)
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QLabel(self.frame_7)
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2, 0, Qt.AlignLeft|Qt.AlignTop)
        self.label_3 = QLabel(self.frame_7)
        self.label_3.setMinimumSize(QSize(32, 32))
        self.label_3.setMaximumSize(QSize(0, 0))
        self.label_3.setText("")
        self.label_3.setPixmap(QPixmap("../../../../Downloads/simplified_logo_no_bg.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3, 0, Qt.AlignLeft|Qt.AlignTop)
        self.verticalLayout_5.addWidget(self.frame_7, 0, Qt.AlignTop)
        self.frame_8 = QFrame(self.slide_menu)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.toolBox = QToolBox(self.frame_8)
        self.toolBox.setCursor(QCursor(Qt.ArrowCursor))
        self.toolBox.setStyleSheet("QToolBox{\n"
"    background-color: rgb(24,24,36);\n"
"    text-align: left;\n"
"}\n"
"QToolBox::tab{\n"
"    border-radius: 5px\n"
"    background-color: rgb(17,16,26);\n"
"    text-align: left;\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.toolBoxPage1 = QWidget()
        self.toolBoxPage1.setGeometry(QRect(0, 0, 199, 408))
        self.toolBoxPage1.setObjectName("toolBoxPage1")
        self.verticalLayout_7 = QVBoxLayout(self.toolBoxPage1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_10 = QFrame(self.toolBoxPage1)
        self.frame_10.setFrameShape(QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_8 = QVBoxLayout(self.frame_10)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_10 = QPushButton(self.frame_10)
        font = QFont()
        font.setPointSize(12)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setCursor(QCursor(Qt.PointingHandCursor))
        icon = QIcon()
        icon.addPixmap(QPixmap(":/icons/icons/database.svg"), QIcon.Normal, QIcon.Off)
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setIconSize(QSize(20, 20))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_8.addWidget(self.pushButton_10, 0, Qt.AlignLeft)
        self.pushButton_12 = QPushButton(self.frame_10)
        font = QFont()
        font.setPointSize(12)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setCursor(QCursor(Qt.PointingHandCursor))
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(":/icons/icons/code.svg"), QIcon.Normal, QIcon.Off)
        self.pushButton_12.setIcon(icon1)
        self.pushButton_12.setIconSize(QSize(20, 20))
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_8.addWidget(self.pushButton_12, 0, Qt.AlignLeft)
        self.pushButton_11 = QPushButton(self.frame_10)
        font = QFont()
        font.setPointSize(12)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setCursor(QCursor(Qt.PointingHandCursor))
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(":/icons/icons/bar-chart-2.svg"), QIcon.Normal, QIcon.Off)
        self.pushButton_11.setIcon(icon2)
        self.pushButton_11.setIconSize(QSize(20, 20))
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_8.addWidget(self.pushButton_11, 0, Qt.AlignLeft)
        self.verticalLayout_7.addWidget(self.frame_10, 0, Qt.AlignTop)
        icon3 = QIcon()
        icon3.addPixmap(QPixmap(":/icons/icons/chevron-down.svg"), QIcon.Normal, QIcon.Off)
        self.toolBox.addItem(self.toolBoxPage1, icon3, "")
        self.toolBoxPage2 = QWidget()
        self.toolBoxPage2.setGeometry(QRect(0, 0, 200, 422))
        self.toolBoxPage2.setObjectName("toolBoxPage2")
        self.verticalLayout_9 = QVBoxLayout(self.toolBoxPage2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_11 = QFrame(self.toolBoxPage2)
        self.frame_11.setFrameShape(QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_13 = QPushButton(self.frame_11)
        font = QFont()
        font.setPointSize(12)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setCursor(QCursor(Qt.PointingHandCursor))
        icon4 = QIcon()
        icon4.addPixmap(QPixmap(":/icons/icons/package.svg"), QIcon.Normal, QIcon.Off)
        self.pushButton_13.setIcon(icon4)
        self.pushButton_13.setIconSize(QSize(20, 20))
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_10.addWidget(self.pushButton_13, 0, Qt.AlignLeft)
        self.pushButton_14 = QPushButton(self.frame_11)
        font = QFont()
        font.setPointSize(12)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setCursor(QCursor(Qt.PointingHandCursor))
        icon5 = QIcon()
        icon5.addPixmap(QPixmap(":/icons/icons/help-circle.svg"), QIcon.Normal, QIcon.Off)
        self.pushButton_14.setIcon(icon5)
        self.pushButton_14.setIconSize(QSize(20, 20))
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_10.addWidget(self.pushButton_14, 0, Qt.AlignLeft)
        self.verticalLayout_9.addWidget(self.frame_11, 0, Qt.AlignTop)
        self.label_4 = QLabel(self.toolBoxPage2)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4, 0, Qt.AlignTop)
        self.toolBox.addItem(self.toolBoxPage2, icon3, "")
        self.verticalLayout_6.addWidget(self.toolBox)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.frame_9 = QFrame(self.slide_menu)
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_9 = QHBoxLayout(self.frame_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.exit_button = QPushButton(self.frame_9)
        icon6 = QIcon()
        icon6.addPixmap(QPixmap(":/icons/icons/external-link.svg"), QIcon.Normal, QIcon.Off)
        self.exit_button.setIcon(icon6)
        self.exit_button.setIconSize(QSize(16, 16))
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout_9.addWidget(self.exit_button, 0, Qt.AlignLeft|Qt.AlignBottom)
        self.verticalLayout_5.addWidget(self.frame_9, 0, Qt.AlignBottom)
        self.verticalLayout_2.addWidget(self.slide_menu)
        self.horizontalLayout.addWidget(self.side_menu_container)
        self.main_body = QFrame(self.centralwidget)
        self.main_body.setFrameShape(QFrame.StyledPanel)
        self.main_body.setFrameShadow(QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.verticalLayout = QVBoxLayout(self.main_body)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QFrame(self.main_body)
        self.header_frame.setStyleSheet("background-color: rgb(9,5,13);")
        self.header_frame.setFrameShape(QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_2 = QHBoxLayout(self.header_frame)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QFrame(self.header_frame)
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.open_close_side_bar_btn = QPushButton(self.frame_6)
        self.open_close_side_bar_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.open_close_side_bar_btn.setStyleSheet("")
        self.open_close_side_bar_btn.setText("")
        icon7 = QIcon()
        icon7.addPixmap(QPixmap(":/icons/icons/menu.svg"), QIcon.Normal, QIcon.Off)
        self.open_close_side_bar_btn.setIcon(icon7)
        self.open_close_side_bar_btn.setIconSize(QSize(32, 32))
        self.open_close_side_bar_btn.setObjectName("open_close_side_bar_btn")
        self.horizontalLayout_7.addWidget(self.open_close_side_bar_btn, 0, Qt.AlignLeft|Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_6, 0, Qt.AlignLeft|Qt.AlignTop)
        self.frame_3 = QFrame(self.header_frame)
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit = QLineEdit(self.frame_3)
        self.lineEdit.setMinimumSize(QSize(200, 0))
        self.lineEdit.setStyleSheet("border-bottom: 3px solid rgb(105, 162, 198);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit, 0, Qt.AlignLeft)
        self.pushButton_6 = QPushButton(self.frame_3)
        self.pushButton_6.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_6.setText("")
        icon8 = QIcon()
        icon8.addPixmap(QPixmap(":/icons/icons/search.svg"), QIcon.Normal, QIcon.Off)
        self.pushButton_6.setIcon(icon8)
        self.pushButton_6.setIconSize(QSize(20, 20))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6, 0, Qt.AlignLeft)
        self.horizontalLayout_2.addWidget(self.frame_3, 0, Qt.AlignLeft|Qt.AlignTop)
        self.frame_2 = QFrame(self.header_frame)
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_5 = QPushButton(self.frame_2)
        self.pushButton_5.setCursor(QCursor(Qt.ForbiddenCursor))
        self.pushButton_5.setText("")
        icon9 = QIcon()
        icon9.addPixmap(QPixmap(":/icons/icons/user.svg"), QIcon.Normal, QIcon.Off)
        self.pushButton_5.setIcon(icon9)
        self.pushButton_5.setIconSize(QSize(20, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.pushButton_4 = QPushButton(self.frame_2)
        self.pushButton_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_4.setText("")
        icon10 = QIcon()
        icon10.addPixmap(QPixmap(":/icons/icons/bell.svg"), QIcon.Normal, QIcon.Off)
        self.pushButton_4.setIcon(icon10)
        self.pushButton_4.setIconSize(QSize(20, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.horizontalLayout_2.addWidget(self.frame_2, 0, Qt.AlignHCenter|Qt.AlignTop)
        self.frame = QFrame(self.header_frame)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minimize_window_button = QPushButton(self.frame)
        self.minimize_window_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.minimize_window_button.setText("")
        icon11 = QIcon()
        icon11.addPixmap(QPixmap(":/icons/icons/arrow-down-left.svg"), QIcon.Normal, QIcon.Off)
        self.minimize_window_button.setIcon(icon11)
        self.minimize_window_button.setIconSize(QSize(20, 20))
        self.minimize_window_button.setObjectName("minimize_window_button")
        self.horizontalLayout_4.addWidget(self.minimize_window_button)
        self.restore_window_button = QPushButton(self.frame)
        self.restore_window_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.restore_window_button.setText("")
        icon12 = QIcon()
        icon12.addPixmap(QPixmap(":/icons/icons/maximize-2.svg"), QIcon.Normal, QIcon.Off)
        self.restore_window_button.setIcon(icon12)
        self.restore_window_button.setObjectName("restore_window_button")
        self.horizontalLayout_4.addWidget(self.restore_window_button)
        self.close_window_button = QPushButton(self.frame)
        self.close_window_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.close_window_button.setText("")
        icon13 = QIcon()
        icon13.addPixmap(QPixmap(":/icons/icons/x.svg"), QIcon.Normal, QIcon.Off)
        self.close_window_button.setIcon(icon13)
        self.close_window_button.setIconSize(QSize(20, 20))
        self.close_window_button.setObjectName("close_window_button")
        self.horizontalLayout_4.addWidget(self.close_window_button)
        self.horizontalLayout_2.addWidget(self.frame, 0, Qt.AlignRight|Qt.AlignTop)
        self.verticalLayout.addWidget(self.header_frame, 0, Qt.AlignTop)
        self.main_body_contents = QFrame(self.main_body)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body_contents.sizePolicy().hasHeightForWidth())
        self.main_body_contents.setSizePolicy(sizePolicy)
        self.main_body_contents.setFrameShape(QFrame.StyledPanel)
        self.main_body_contents.setFrameShadow(QFrame.Raised)
        self.main_body_contents.setObjectName("main_body_contents")
        self.verticalLayout_11 = QVBoxLayout(self.main_body_contents)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_5 = QLabel(self.main_body_contents)
        self.label_5.setMinimumSize(QSize(600, 300))
        self.label_5.setMaximumSize(QSize(200, 200))
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setTextFormat(Qt.AutoText)
        self.label_5.setPixmap(QPixmap("../../../../Downloads/logo_no_bg.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5, 0, Qt.AlignHCenter|Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.main_body_contents, 0, Qt.AlignVCenter)
        self.footer = QFrame(self.main_body)
        self.footer.setFrameShape(QFrame.StyledPanel)
        self.footer.setFrameShadow(QFrame.Raised)
        self.footer.setObjectName("footer")
        self.horizontalLayout_3 = QHBoxLayout(self.footer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QFrame(self.footer)
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QFrame(self.footer)
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.site_button = QPushButton(self.frame_5)
        self.site_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.site_button.setMouseTracking(False)
        self.site_button.setText("")
        icon14 = QIcon()
        icon14.addPixmap(QPixmap(":/icons/icons/box.svg"), QIcon.Normal, QIcon.Off)
        self.site_button.setIcon(icon14)
        self.site_button.setObjectName("site_button")
        self.verticalLayout_3.addWidget(self.site_button, 0, Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.size_grip = QFrame(self.footer)
        self.size_grip.setMinimumSize(QSize(10, 10))
        self.size_grip.setMaximumSize(QSize(10, 10))
        self.size_grip.setCursor(QCursor(Qt.SizeFDiagCursor))
        self.size_grip.setFrameShape(QFrame.StyledPanel)
        self.size_grip.setFrameShadow(QFrame.Raised)
        self.size_grip.setObjectName("size_grip")
        self.horizontalLayout_3.addWidget(self.size_grip, 0, Qt.AlignRight|Qt.AlignBottom)
        self.verticalLayout.addWidget(self.footer, 0, Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.main_body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "ERGOAWARE"))
        self.pushButton_10.setText(_translate("MainWindow", "Workstation Calibration"))
        self.pushButton_12.setText(_translate("MainWindow", "Robot Launch                    "))
        self.pushButton_11.setText(_translate("MainWindow", "Analyze                                "))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage1), _translate("MainWindow", "Control Panel"))
        self.pushButton_13.setText(_translate("MainWindow", "Installation                         "))
        self.pushButton_14.setText(_translate("MainWindow", "Help                                      "))
        self.label_4.setText(_translate("MainWindow", "Some text"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage2), _translate("MainWindow", "Settings"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search"))
        self.label.setText(_translate("MainWindow", "Ergoware UI v2.0"))
import icons_rc
