# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PySide2.QtCore import * 
from PySide2.QtGui import * 
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(836, 545)
        MainWindow.setStyleSheet("*{\n"
"    border: none;\n"
"    color: white;\n"
"}\n"
"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(24,24,36);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu_container = QFrame(self.centralwidget)
        self.side_menu_container.setMinimumSize(QSize(0, 0))
        self.side_menu_container.setMaximumSize(QSize(0, 16777215))
        self.side_menu_container.setStyleSheet("background-color: rgb(9,5,13);")
        self.side_menu_container.setFrameShape(QFrame.StyledPanel)
        self.side_menu_container.setFrameShadow(QFrame.Raised)
        self.side_menu_container.setObjectName("side_menu_container")
        self.verticalLayout_2 = QVBoxLayout(self.side_menu_container)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.slide_menu = QFrame(self.side_menu_container)
        self.slide_menu.setMinimumSize(QSize(198, 0))
        self.slide_menu.setFrameShape(QFrame.StyledPanel)
        self.slide_menu.setFrameShadow(QFrame.Raised)
        self.slide_menu.setObjectName("slide_menu")
        self.verticalLayout_5 = QVBoxLayout(self.slide_menu)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_7 = QFrame(self.slide_menu)
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_8 = QHBoxLayout(self.frame_7)
        self.horizontalLayout_8.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ergoaware_button = QPushButton(self.frame_7)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ergoaware_button.sizePolicy().hasHeightForWidth())
        self.ergoaware_button.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ergoaware_button.setFont(font)
        self.ergoaware_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.ergoaware_button.setObjectName("ergoaware_button")
        self.horizontalLayout_8.addWidget(self.ergoaware_button)
        self.ergoaware_logo_button = QPushButton(self.frame_7)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ergoaware_logo_button.sizePolicy().hasHeightForWidth())
        self.ergoaware_logo_button.setSizePolicy(sizePolicy)
        self.ergoaware_logo_button.setMinimumSize(QSize(0, 32))
        self.ergoaware_logo_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.ergoaware_logo_button.setText("")
        icon = QIcon()
        icon.addPixmap(QPixmap("simplified_logo_no_bg.png"), QIcon.Normal, QIcon.Off)
        self.ergoaware_logo_button.setIcon(icon)
        self.ergoaware_logo_button.setIconSize(QSize(40, 32))
        self.ergoaware_logo_button.setObjectName("ergoaware_logo_button")
        self.horizontalLayout_8.addWidget(self.ergoaware_logo_button)
        self.verticalLayout_5.addWidget(self.frame_7, 0, Qt.AlignTop)
        self.frame_8 = QFrame(self.slide_menu)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.toolBox = QToolBox(self.frame_8)
        self.toolBox.setCursor(QCursor(Qt.ArrowCursor))
        self.toolBox.setStyleSheet("QToolBox{\n"
"    background-color: rgb(24,24,36);\n"
"    text-align: left;\n"
"}\n"
"QToolBox::tab{\n"
"    border-radius: 5px\n"
"    background-color: rgb(17,16,26);\n"
"    text-align: left;\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.toolBoxPage1 = QWidget()
        self.toolBoxPage1.setGeometry(QRect(0, 0, 198, 422))
        self.toolBoxPage1.setObjectName("toolBoxPage1")
        self.verticalLayout_7 = QVBoxLayout(self.toolBoxPage1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_10 = QFrame(self.toolBoxPage1)
        self.frame_10.setFrameShape(QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_8 = QVBoxLayout(self.frame_10)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.calibration_button = QPushButton(self.frame_10)
        self.calibration_button.setMinimumSize(QSize(0, 35))
        font = QFont()
        font.setPointSize(12)
        self.calibration_button.setFont(font)
        self.calibration_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.calibration_button.setMouseTracking(False)
        self.calibration_button.setStyleSheet("")
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(":/icons/icons/database.svg"), QIcon.Normal, QIcon.Off)
        self.calibration_button.setIcon(icon1)
        self.calibration_button.setIconSize(QSize(20, 20))
        self.calibration_button.setObjectName("calibration_button")
        self.verticalLayout_8.addWidget(self.calibration_button, 0, Qt.AlignLeft)
        self.launch_button = QPushButton(self.frame_10)
        self.launch_button.setMinimumSize(QSize(0, 35))
        font = QFont()
        font.setPointSize(12)
        self.launch_button.setFont(font)
        self.launch_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(":/icons/icons/code.svg"), QIcon.Normal, QIcon.Off)
        self.launch_button.setIcon(icon2)
        self.launch_button.setIconSize(QSize(20, 20))
        self.launch_button.setObjectName("launch_button")
        self.verticalLayout_8.addWidget(self.launch_button, 0, Qt.AlignLeft)
        self.analyze_button = QPushButton(self.frame_10)
        self.analyze_button.setMinimumSize(QSize(0, 35))
        font = QFont()
        font.setPointSize(12)
        self.analyze_button.setFont(font)
        self.analyze_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon3 = QIcon()
        icon3.addPixmap(QPixmap(":/icons/icons/bar-chart-2.svg"), QIcon.Normal, QIcon.Off)
        self.analyze_button.setIcon(icon3)
        self.analyze_button.setIconSize(QSize(20, 20))
        self.analyze_button.setObjectName("analyze_button")
        self.verticalLayout_8.addWidget(self.analyze_button, 0, Qt.AlignLeft)
        self.verticalLayout_7.addWidget(self.frame_10, 0, Qt.AlignTop)
        icon4 = QIcon()
        icon4.addPixmap(QPixmap(":/icons/icons/chevron-down.svg"), QIcon.Normal, QIcon.Off)
        self.toolBox.addItem(self.toolBoxPage1, icon4, "")
        self.toolBoxPage2 = QWidget()
        self.toolBoxPage2.setGeometry(QRect(0, 0, 199, 408))
        self.toolBoxPage2.setObjectName("toolBoxPage2")
        self.verticalLayout_9 = QVBoxLayout(self.toolBoxPage2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_11 = QFrame(self.toolBoxPage2)
        self.frame_11.setFrameShape(QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.installation_button = QPushButton(self.frame_11)
        self.installation_button.setMinimumSize(QSize(0, 35))
        font = QFont()
        font.setPointSize(12)
        self.installation_button.setFont(font)
        self.installation_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon5 = QIcon()
        icon5.addPixmap(QPixmap(":/icons/icons/package.svg"), QIcon.Normal, QIcon.Off)
        self.installation_button.setIcon(icon5)
        self.installation_button.setIconSize(QSize(20, 20))
        self.installation_button.setObjectName("installation_button")
        self.verticalLayout_10.addWidget(self.installation_button, 0, Qt.AlignLeft)
        self.help_button = QPushButton(self.frame_11)
        self.help_button.setMinimumSize(QSize(0, 35))
        font = QFont()
        font.setPointSize(12)
        self.help_button.setFont(font)
        self.help_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon6 = QIcon()
        icon6.addPixmap(QPixmap(":/icons/icons/help-circle.svg"), QIcon.Normal, QIcon.Off)
        self.help_button.setIcon(icon6)
        self.help_button.setIconSize(QSize(20, 20))
        self.help_button.setObjectName("help_button")
        self.verticalLayout_10.addWidget(self.help_button, 0, Qt.AlignLeft)
        self.verticalLayout_9.addWidget(self.frame_11, 0, Qt.AlignTop)
        self.toolBox.addItem(self.toolBoxPage2, icon4, "")
        self.verticalLayout_6.addWidget(self.toolBox)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.frame_9 = QFrame(self.slide_menu)
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_9 = QHBoxLayout(self.frame_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.exit_button = QPushButton(self.frame_9)
        self.exit_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon7 = QIcon()
        icon7.addPixmap(QPixmap(":/icons/icons/external-link.svg"), QIcon.Normal, QIcon.Off)
        self.exit_button.setIcon(icon7)
        self.exit_button.setIconSize(QSize(16, 16))
        self.exit_button.setObjectName("exit_button")
        self.horizontalLayout_9.addWidget(self.exit_button, 0, Qt.AlignLeft|Qt.AlignBottom)
        self.verticalLayout_5.addWidget(self.frame_9, 0, Qt.AlignBottom)
        self.verticalLayout_2.addWidget(self.slide_menu)
        self.horizontalLayout.addWidget(self.side_menu_container)
        self.main_body = QFrame(self.centralwidget)
        self.main_body.setFrameShape(QFrame.StyledPanel)
        self.main_body.setFrameShadow(QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.verticalLayout = QVBoxLayout(self.main_body)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QFrame(self.main_body)
        self.header_frame.setStyleSheet("background-color: rgb(9,5,13);")
        self.header_frame.setFrameShape(QFrame.StyledPanel)
        self.header_frame.setFrameShadow(QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_2 = QHBoxLayout(self.header_frame)
        self.horizontalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_6 = QFrame(self.header_frame)
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_7 = QHBoxLayout(self.frame_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.open_close_side_bar_btn = QPushButton(self.frame_6)
        self.open_close_side_bar_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.open_close_side_bar_btn.setStyleSheet("")
        self.open_close_side_bar_btn.setText("")
        icon8 = QIcon()
        icon8.addPixmap(QPixmap(":/icons/icons/menu.svg"), QIcon.Normal, QIcon.Off)
        self.open_close_side_bar_btn.setIcon(icon8)
        self.open_close_side_bar_btn.setIconSize(QSize(32, 32))
        self.open_close_side_bar_btn.setObjectName("open_close_side_bar_btn")
        self.horizontalLayout_7.addWidget(self.open_close_side_bar_btn, 0, Qt.AlignLeft|Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_6, 0, Qt.AlignLeft|Qt.AlignTop)
        self.frame_3 = QFrame(self.header_frame)
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit = QLineEdit(self.frame_3)
        self.lineEdit.setMinimumSize(QSize(200, 0))
        self.lineEdit.setStyleSheet("border-bottom: 3px solid rgb(105, 162, 198);")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.lineEdit, 0, Qt.AlignLeft)
        self.pushButton_6 = QPushButton(self.frame_3)
        self.pushButton_6.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_6.setText("")
        icon9 = QIcon()
        icon9.addPixmap(QPixmap(":/icons/icons/search.svg"), QIcon.Normal, QIcon.Off)
        self.pushButton_6.setIcon(icon9)
        self.pushButton_6.setIconSize(QSize(20, 20))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6, 0, Qt.AlignLeft)
        self.horizontalLayout_2.addWidget(self.frame_3, 0, Qt.AlignLeft|Qt.AlignTop)
        self.frame_2 = QFrame(self.header_frame)
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_5 = QPushButton(self.frame_2)
        self.pushButton_5.setCursor(QCursor(Qt.ForbiddenCursor))
        self.pushButton_5.setText("")
        icon10 = QIcon()
        icon10.addPixmap(QPixmap(":/icons/icons/user.svg"), QIcon.Normal, QIcon.Off)
        self.pushButton_5.setIcon(icon10)
        self.pushButton_5.setIconSize(QSize(20, 20))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        self.pushButton_4 = QPushButton(self.frame_2)
        self.pushButton_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_4.setText("")
        icon11 = QIcon()
        icon11.addPixmap(QPixmap(":/icons/icons/bell.svg"), QIcon.Normal, QIcon.Off)
        self.pushButton_4.setIcon(icon11)
        self.pushButton_4.setIconSize(QSize(20, 20))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_5.addWidget(self.pushButton_4)
        self.horizontalLayout_2.addWidget(self.frame_2, 0, Qt.AlignHCenter|Qt.AlignTop)
        self.frame = QFrame(self.header_frame)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minimize_window_button = QPushButton(self.frame)
        self.minimize_window_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.minimize_window_button.setText("")
        icon12 = QIcon()
        icon12.addPixmap(QPixmap(":/icons/icons/arrow-down-left.svg"), QIcon.Normal, QIcon.Off)
        self.minimize_window_button.setIcon(icon12)
        self.minimize_window_button.setIconSize(QSize(20, 20))
        self.minimize_window_button.setObjectName("minimize_window_button")
        self.horizontalLayout_4.addWidget(self.minimize_window_button)
        self.restore_window_button = QPushButton(self.frame)
        self.restore_window_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.restore_window_button.setText("")
        icon13 = QIcon()
        icon13.addPixmap(QPixmap(":/icons/icons/maximize-2.svg"), QIcon.Normal, QIcon.Off)
        self.restore_window_button.setIcon(icon13)
        self.restore_window_button.setObjectName("restore_window_button")
        self.horizontalLayout_4.addWidget(self.restore_window_button)
        self.close_window_button = QPushButton(self.frame)
        self.close_window_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.close_window_button.setText("")
        icon14 = QIcon()
        icon14.addPixmap(QPixmap(":/icons/icons/x.svg"), QIcon.Normal, QIcon.Off)
        self.close_window_button.setIcon(icon14)
        self.close_window_button.setIconSize(QSize(20, 20))
        self.close_window_button.setObjectName("close_window_button")
        self.horizontalLayout_4.addWidget(self.close_window_button)
        self.horizontalLayout_2.addWidget(self.frame, 0, Qt.AlignRight|Qt.AlignTop)
        self.verticalLayout.addWidget(self.header_frame, 0, Qt.AlignTop)
        self.main_body_contents = QFrame(self.main_body)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_body_contents.sizePolicy().hasHeightForWidth())
        self.main_body_contents.setSizePolicy(sizePolicy)
        self.main_body_contents.setFrameShape(QFrame.StyledPanel)
        self.main_body_contents.setFrameShadow(QFrame.Raised)
        self.main_body_contents.setObjectName("main_body_contents")
        self.verticalLayout_11 = QVBoxLayout(self.main_body_contents)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pages = QStackedWidget(self.main_body_contents)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pages.sizePolicy().hasHeightForWidth())
        self.pages.setSizePolicy(sizePolicy)
        self.pages.setStyleSheet("")
        self.pages.setObjectName("pages")
        self.home = QWidget()
        self.home.setObjectName("home")
        self.verticalLayout_12 = QVBoxLayout(self.home)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_5 = QLabel(self.home)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QSize(800, 400))
        self.label_5.setText("")
        self.label_5.setPixmap(QPixmap("logo_no_bg.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.label_5, 0, Qt.AlignHCenter)
        self.pages.addWidget(self.home)
        self.calibration = QWidget()
        self.calibration.setObjectName("calibration")
        self.verticalLayout_13 = QVBoxLayout(self.calibration)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_12 = QFrame(self.calibration)
        self.frame_12.setFrameShape(QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_10 = QHBoxLayout(self.frame_12)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_14 = QFrame(self.frame_12)
        self.frame_14.setFrameShape(QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_15 = QVBoxLayout(self.frame_14)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_2 = QLabel(self.frame_14)
        self.label_2.setMinimumSize(QSize(0, 40))
        self.label_2.setMaximumSize(QSize(16777215, 40))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(68, 84, 106);\n"
"padding-top: -12px;\n"
"border: 1px solid black;\n"
"border-radius: 4px;")
        self.label_2.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_15.addWidget(self.label_2, 0, Qt.AlignTop)
        self.frame_17 = QFrame(self.frame_14)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setMinimumSize(QSize(0, 320))
        self.frame_17.setFrameShape(QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_16 = QVBoxLayout(self.frame_17)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.radioButton = QRadioButton(self.frame_17)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton.sizePolicy().hasHeightForWidth())
        self.radioButton.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setCursor(QCursor(Qt.ForbiddenCursor))
        self.radioButton.setStyleSheet("color: rgb(140, 184, 198);")
        self.radioButton.setCheckable(True)
        self.radioButton.setChecked(False)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_16.addWidget(self.radioButton)
        self.radioButton_2 = QRadioButton(self.frame_17)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_2.sizePolicy().hasHeightForWidth())
        self.radioButton_2.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setCursor(QCursor(Qt.ForbiddenCursor))
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_16.addWidget(self.radioButton_2)
        self.radioButton_3 = QRadioButton(self.frame_17)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_3.sizePolicy().hasHeightForWidth())
        self.radioButton_3.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(12)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setCursor(QCursor(Qt.ForbiddenCursor))
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_16.addWidget(self.radioButton_3)
        self.radioButton_4 = QRadioButton(self.frame_17)
        sizePolicy = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_4.sizePolicy().hasHeightForWidth())
        self.radioButton_4.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(12)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setCursor(QCursor(Qt.ForbiddenCursor))
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_16.addWidget(self.radioButton_4)
        self.verticalLayout_15.addWidget(self.frame_17)
        self.horizontalLayout_10.addWidget(self.frame_14)
        self.frame_15 = QFrame(self.frame_12)
        self.frame_15.setFrameShape(QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_17 = QVBoxLayout(self.frame_15)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_3 = QLabel(self.frame_15)
        self.label_3.setMinimumSize(QSize(0, 40))
        self.label_3.setMaximumSize(QSize(16777215, 40))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(68, 84, 106);\n"
"padding-top: -12px;\n"
"border: 1px solid black;\n"
"border-radius: 4px;")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_17.addWidget(self.label_3, 0, Qt.AlignTop)
        self.label_6 = QLabel(self.frame_15)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QSize(0, 320))
        self.label_6.setMaximumSize(QSize(320, 16777215))
        self.label_6.setStyleSheet("background-color: rgb(140, 184, 198);\n"
"margin-top: 20px;\n"
"border-radius: 2px;")
        self.label_6.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_17.addWidget(self.label_6)
        self.horizontalLayout_10.addWidget(self.frame_15)
        self.frame_16 = QFrame(self.frame_12)
        self.frame_16.setFrameShape(QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_18 = QVBoxLayout(self.frame_16)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_7 = QLabel(self.frame_16)
        self.label_7.setMinimumSize(QSize(0, 40))
        self.label_7.setMaximumSize(QSize(16777215, 40))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(68, 84, 106);\n"
"padding-top: -12px;\n"
"border: 1px solid black;\n"
"border-radius: 4px;")
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_18.addWidget(self.label_7, 0, Qt.AlignTop)
        self.label_8 = QLabel(self.frame_16)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QSize(0, 0))
        self.label_8.setSizeIncrement(QSize(0, 270))
        self.label_8.setStyleSheet("background-color: rgb(140, 184, 198);\n"
"margin-top: 20px;\n"
"border-radius: 2px;")
        self.label_8.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_18.addWidget(self.label_8)
        self.comboBox = QComboBox(self.frame_16)
        self.comboBox.setMinimumSize(QSize(0, 30))
        self.comboBox.setCursor(QCursor(Qt.ForbiddenCursor))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_18.addWidget(self.comboBox)
        self.pushButton_2 = QPushButton(self.frame_16)
        self.pushButton_2.setMinimumSize(QSize(0, 40))
        self.pushButton_2.setCursor(QCursor(Qt.ForbiddenCursor))
        self.pushButton_2.setStyleSheet("border: 1px solid rgb(140, 184, 198);")
        icon15 = QIcon()
        icon15.addPixmap(QPixmap(":/icons/icons/chevrons-up.svg"), QIcon.Normal, QIcon.Off)
        self.pushButton_2.setIcon(icon15)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_18.addWidget(self.pushButton_2)
        self.horizontalLayout_10.addWidget(self.frame_16)
        self.verticalLayout_13.addWidget(self.frame_12)
        self.frame_13 = QFrame(self.calibration)
        self.frame_13.setMaximumSize(QSize(16777215, 50))
        self.frame_13.setFrameShape(QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_14 = QVBoxLayout(self.frame_13)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.launch_button_2 = QPushButton(self.frame_13)
        self.launch_button_2.setMinimumSize(QSize(0, 30))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.launch_button_2.setFont(font)
        self.launch_button_2.setStyleSheet("background-color: rgb(68, 84, 106);\n"
"color: rgb(140, 184, 198);\n"
"border: 1px solid rgb(140, 184, 198);\n"
"border-radius: 10px;")
        icon16 = QIcon()
        icon16.addPixmap(QPixmap(":/icons/icons/command.svg"), QIcon.Normal, QIcon.Off)
        self.launch_button_2.setIcon(icon16)
        self.launch_button_2.setObjectName("launch_button_2")
        self.verticalLayout_14.addWidget(self.launch_button_2)
        self.verticalLayout_13.addWidget(self.frame_13)
        self.pages.addWidget(self.calibration)
        self.launch = QWidget()
        self.launch.setAutoFillBackground(False)
        self.launch.setStyleSheet("")
        self.launch.setObjectName("launch")
        self.verticalLayout_19 = QVBoxLayout(self.launch)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_18 = QFrame(self.launch)
        self.frame_18.setFrameShape(QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_13 = QHBoxLayout(self.frame_18)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_10 = QLabel(self.frame_18)
        font = QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.frame_20 = QFrame(self.frame_18)
        self.frame_20.setFrameShape(QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_22 = QVBoxLayout(self.frame_20)
        self.verticalLayout_22.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(30)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.comboBox_3 = QComboBox(self.frame_20)
        self.comboBox_3.setMinimumSize(QSize(300, 0))
        font = QFont()
        font.setPointSize(13)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.comboBox_3.setStyleSheet("border-bottom: 3px solid rgb(140, 184, 198);\n"
"padding-bottom: 2px;")
        self.comboBox_3.setIconSize(QSize(16, 16))
        self.comboBox_3.setDuplicatesEnabled(False)
        self.comboBox_3.setFrame(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_22.addWidget(self.comboBox_3, 0, Qt.AlignHCenter|Qt.AlignVCenter)
        self.pushButton_7 = QPushButton(self.frame_20)
        self.pushButton_7.setMinimumSize(QSize(300, 0))
        self.pushButton_7.setMaximumSize(QSize(500, 16777215))
        font = QFont()
        font.setPointSize(13)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("background-color: rgb(68, 84, 106);\n"
"color: rgb(140, 184, 198);\n"
"border: 1px solid rgb(140, 184, 198);\n"
"border-radius: 10px;")
        icon17 = QIcon()
        icon17.addPixmap(QPixmap(":/icons/icons/terminal.svg"), QIcon.Normal, QIcon.Off)
        self.pushButton_7.setIcon(icon17)
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_22.addWidget(self.pushButton_7, 0, Qt.AlignHCenter|Qt.AlignTop)
        self.horizontalLayout_13.addWidget(self.frame_20, 0, Qt.AlignVCenter)
        self.verticalLayout_19.addWidget(self.frame_18)
        self.pages.addWidget(self.launch)
        self.analyze = QWidget()
        self.analyze.setObjectName("analyze")
        self.pages.addWidget(self.analyze)
        self.installation = QWidget()
        self.installation.setObjectName("installation")
        self.horizontalLayout_14 = QHBoxLayout(self.installation)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_19 = QFrame(self.installation)
        self.frame_19.setFrameShape(QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_12 = QHBoxLayout(self.frame_19)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_21 = QFrame(self.frame_19)
        self.frame_21.setMinimumSize(QSize(0, 0))
        self.frame_21.setFrameShape(QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_23 = QVBoxLayout(self.frame_21)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_11 = QLabel(self.frame_21)
        self.label_11.setMinimumSize(QSize(500, 0))
        font = QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_23.addWidget(self.label_11)
        self.horizontalLayout_12.addWidget(self.frame_21)
        self.frame_22 = QFrame(self.frame_19)
        self.frame_22.setFrameShape(QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_20 = QVBoxLayout(self.frame_22)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(10)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.packages_list = QListWidget(self.frame_22)
        font = QFont()
        font.setPointSize(13)
        self.packages_list.setFont(font)
        self.packages_list.setStyleSheet("background-color: rgb(140, 184, 198);\n"
"color: rgb(0, 0, 0);\n"
"border: 1px solid rgb(140, 184, 198);\n"
"border-radius: 5px;")
        self.packages_list.setObjectName("packages_list")
        item = QListWidgetItem()
        item.setCheckState(Qt.Unchecked)
        self.packages_list.addItem(item)
        item = QListWidgetItem()
        item.setCheckState(Qt.Unchecked)
        self.packages_list.addItem(item)
        item = QListWidgetItem()
        item.setCheckState(Qt.Unchecked)
        self.packages_list.addItem(item)
        item = QListWidgetItem()
        item.setCheckState(Qt.Unchecked)
        self.packages_list.addItem(item)
        item = QListWidgetItem()
        item.setCheckState(Qt.Unchecked)
        self.packages_list.addItem(item)
        item = QListWidgetItem()
        item.setCheckState(Qt.Unchecked)
        self.packages_list.addItem(item)
        item = QListWidgetItem()
        item.setCheckState(Qt.Unchecked)
        self.packages_list.addItem(item)
        item = QListWidgetItem()
        item.setCheckState(Qt.Unchecked)
        self.packages_list.addItem(item)
        item = QListWidgetItem()
        item.setCheckState(Qt.Unchecked)
        self.packages_list.addItem(item)
        item = QListWidgetItem()
        item.setCheckState(Qt.Unchecked)
        self.packages_list.addItem(item)
        self.verticalLayout_20.addWidget(self.packages_list)
        self.frame_24 = QFrame(self.frame_22)
        self.frame_24.setMinimumSize(QSize(0, 100))
        self.frame_24.setFrameShape(QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_24 = QVBoxLayout(self.frame_24)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_23 = QFrame(self.frame_24)
        self.frame_23.setFrameShape(QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_15 = QHBoxLayout(self.frame_23)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(10)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.select_all_button = QPushButton(self.frame_23)
        font = QFont()
        font.setPointSize(13)
        self.select_all_button.setFont(font)
        self.select_all_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.select_all_button.setStyleSheet("border: 1px solid rgb(140, 184, 198);")
        icon18 = QIcon()
        icon18.addPixmap(QPixmap(":/icons/icons/check.svg"), QIcon.Normal, QIcon.Off)
        self.select_all_button.setIcon(icon18)
        self.select_all_button.setObjectName("select_all_button")
        self.horizontalLayout_15.addWidget(self.select_all_button)
        self.unselect_all_button = QPushButton(self.frame_23)
        font = QFont()
        font.setPointSize(13)
        self.unselect_all_button.setFont(font)
        self.unselect_all_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.unselect_all_button.setStyleSheet("border: 1px solid rgb(140, 184, 198);")
        icon19 = QIcon()
        icon19.addPixmap(QPixmap(":/icons/icons/square.svg"), QIcon.Normal, QIcon.Off)
        self.unselect_all_button.setIcon(icon19)
        self.unselect_all_button.setObjectName("unselect_all_button")
        self.horizontalLayout_15.addWidget(self.unselect_all_button)
        self.verticalLayout_24.addWidget(self.frame_23)
        self.frame_25 = QFrame(self.frame_24)
        self.frame_25.setFrameShape(QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_25 = QVBoxLayout(self.frame_25)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.install_button = QPushButton(self.frame_25)
        self.install_button.setMinimumSize(QSize(0, 30))
        font = QFont()
        font.setPointSize(13)
        self.install_button.setFont(font)
        self.install_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.install_button.setStyleSheet("color: rgb(140, 184, 198);\n"
"background-color: rgb(68, 84, 106);\n"
"border: 1px solid rgb(140, 184, 198);\n"
"border-radius: 10px;")
        icon20 = QIcon()
        icon20.addPixmap(QPixmap(":/icons/icons/download.svg"), QIcon.Normal, QIcon.Off)
        self.install_button.setIcon(icon20)
        self.install_button.setObjectName("install_button")
        self.verticalLayout_25.addWidget(self.install_button)
        self.verticalLayout_24.addWidget(self.frame_25)
        self.verticalLayout_20.addWidget(self.frame_24)
        self.horizontalLayout_12.addWidget(self.frame_22)
        self.horizontalLayout_14.addWidget(self.frame_19)
        self.pages.addWidget(self.installation)
        self.help = QWidget()
        self.help.setObjectName("help")
        self.verticalLayout_26 = QVBoxLayout(self.help)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_26 = QFrame(self.help)
        self.frame_26.setMaximumSize(QSize(16777215, 70))
        self.frame_26.setFrameShape(QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_16 = QHBoxLayout(self.frame_26)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QLabel(self.frame_26)
        self.label_13.setMaximumSize(QSize(358, 16777215))
        self.label_13.setStyleSheet("margin-top: 5px;")
        self.label_13.setText("")
        self.label_13.setPixmap(QPixmap(":/icons/icons/help-circle.svg"))
        self.label_13.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        self.label_12 = QLabel(self.frame_26)
        font = QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QFont.PreferDefault)
        self.label_12.setFont(font)
        self.label_12.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_16.addWidget(self.label_12)
        self.verticalLayout_26.addWidget(self.frame_26)
        self.frame_27 = QFrame(self.help)
        self.frame_27.setFrameShape(QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_26.addWidget(self.frame_27)
        self.pages.addWidget(self.help)
        self.verticalLayout_11.addWidget(self.pages)
        self.verticalLayout.addWidget(self.main_body_contents)
        self.footer = QFrame(self.main_body)
        self.footer.setFrameShape(QFrame.StyledPanel)
        self.footer.setFrameShadow(QFrame.Raised)
        self.footer.setObjectName("footer")
        self.horizontalLayout_3 = QHBoxLayout(self.footer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_4 = QFrame(self.footer)
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_4 = QVBoxLayout(self.frame_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QLabel(self.frame_4)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label, 0, Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.frame_4)
        self.frame_5 = QFrame(self.footer)
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.site_button = QPushButton(self.frame_5)
        self.site_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.site_button.setMouseTracking(False)
        self.site_button.setText("")
        icon21 = QIcon()
        icon21.addPixmap(QPixmap(":/icons/icons/box.svg"), QIcon.Normal, QIcon.Off)
        self.site_button.setIcon(icon21)
        self.site_button.setObjectName("site_button")
        self.verticalLayout_3.addWidget(self.site_button, 0, Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.frame_5)
        self.size_grip = QFrame(self.footer)
        self.size_grip.setMinimumSize(QSize(10, 10))
        self.size_grip.setMaximumSize(QSize(10, 10))
        self.size_grip.setCursor(QCursor(Qt.SizeFDiagCursor))
        self.size_grip.setFrameShape(QFrame.StyledPanel)
        self.size_grip.setFrameShadow(QFrame.Raised)
        self.size_grip.setObjectName("size_grip")
        self.horizontalLayout_3.addWidget(self.size_grip, 0, Qt.AlignRight|Qt.AlignBottom)
        self.verticalLayout.addWidget(self.footer, 0, Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.main_body)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pages.setCurrentIndex(0)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ergoaware_button.setText(_translate("MainWindow", "ERGOAWARE"))
        self.calibration_button.setText(_translate("MainWindow", "Workstation Calibration"))
        self.launch_button.setText(_translate("MainWindow", "Robot Launch                   "))
        self.analyze_button.setText(_translate("MainWindow", "Analyze                               "))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage1), _translate("MainWindow", "Control Panel"))
        self.installation_button.setText(_translate("MainWindow", "Installation                         "))
        self.help_button.setText(_translate("MainWindow", "Help                                      "))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage2), _translate("MainWindow", "Settings"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Configuration"))
        self.radioButton.setText(_translate("MainWindow", "UL0"))
        self.radioButton_2.setText(_translate("MainWindow", "UL1"))
        self.radioButton_3.setText(_translate("MainWindow", "UL2"))
        self.radioButton_4.setText(_translate("MainWindow", "UL3"))
        self.label_3.setText(_translate("MainWindow", "Saved Poses"))
        self.label_6.setText(_translate("MainWindow", "Grasp Pose:\n"
"Reference Frame: \n"
"Position:\n"
"  x:0.0 y:0.0 z:0.0\n"
"Orientation:\n"
"  w:0.0 x:0.0, y:0.0, z:0.0\n"
"Approach Pose:\n"
"Reference Frame: workstation\n"
"Position:\n"
"  x:1.4478104856532081 y:-0.516114496815111 z:1.3787413518368665\n"
"Orientation:\n"
"  w:-0.009251995741633975 x:0.038691735266183136, y:0.9696626116552871, z:-0.24118824547381373"))
        self.label_7.setText(_translate("MainWindow", "Reference Frame"))
        self.label_8.setText(_translate("MainWindow", "Position:\n"
"  x:0.0 y:0.0 z:0.0\n"
"Orientation:\n"
"  w:0.0 x:0.0, y:0.0, z:0.0"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Workstation"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Base"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Tolo"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Gripper"))
        self.pushButton_2.setText(_translate("MainWindow", "Set Grasp Position"))
        self.launch_button_2.setText(_translate("MainWindow", "Launch Robot"))
        self.label_10.setText(_translate("MainWindow", "What do you want to do?"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Choose an option"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Framework"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Robot"))
        self.pushButton_7.setText(_translate("MainWindow", "Run"))
        self.label_11.setText(_translate("MainWindow", "Select all the packages you want to install:"))
        __sortingEnabled = self.packages_list.isSortingEnabled()
        self.packages_list.setSortingEnabled(False)
        item = self.packages_list.item(0)
        item.setText(_translate("MainWindow", "package1"))
        item = self.packages_list.item(1)
        item.setText(_translate("MainWindow", "package2"))
        item = self.packages_list.item(2)
        item.setText(_translate("MainWindow", "package3"))
        item = self.packages_list.item(3)
        item.setText(_translate("MainWindow", "package4"))
        item = self.packages_list.item(4)
        item.setText(_translate("MainWindow", "package5"))
        item = self.packages_list.item(5)
        item.setText(_translate("MainWindow", "package6"))
        item = self.packages_list.item(6)
        item.setText(_translate("MainWindow", "package7"))
        item = self.packages_list.item(7)
        item.setText(_translate("MainWindow", "package8"))
        item = self.packages_list.item(8)
        item.setText(_translate("MainWindow", "package9"))
        item = self.packages_list.item(9)
        item.setText(_translate("MainWindow", "package10"))
        self.packages_list.setSortingEnabled(__sortingEnabled)
        self.select_all_button.setText(_translate("MainWindow", "Select all"))
        self.unselect_all_button.setText(_translate("MainWindow", "Unselect all"))
        self.install_button.setText(_translate("MainWindow", "INSTALL"))
        self.label_12.setText(_translate("MainWindow", "Help"))
        self.label.setText(_translate("MainWindow", "Ergoware UI v2.0"))
import icons_rc